export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'build',
        'ci',
        'chore',
        'revert',
      ],
    ],
    'scope-enum': [
      2,
      'always',
      [
        'selenium',
        'cypress',
        'vibium',
        'appium',
        'mcp',
        'domains',
        'skills',
        'agents',
        'manifests',
        'release',
        'gitflow',
        'ci',
        'docs',
        'deps',
        'config',
        'workflow',
        'contributing',
      ],
    ],
    'scope-empty': [2, 'never'],
    'subject-case': [2, 'never', ['sentence-case', 'start-case', 'pascal-case', 'upper-case']],
    'subject-empty': [2, 'never'],
    'subject-full-stop': [2, 'never', '.'],
  },
  prompt: {
    scopes: [
      { name: 'selenium:     Selenium framework tools and skills', value: 'selenium' },
      { name: 'cypress:      Cypress framework tools and skills', value: 'cypress' },
      { name: 'vibium:       Vibium framework tools and skills', value: 'vibium' },
      { name: 'appium:       Appium mobile automation tools and skills', value: 'appium' },
      { name: 'mcp:          Model Context Protocol server runtime & protocol', value: 'mcp' },
      { name: 'domains:      Domain tools, resources, and reference docs', value: 'domains' },
      { name: 'skills:       Agent testing skills and prompts', value: 'skills' },
      { name: 'agents:       SDET agent personas and directives', value: 'agents' },
      { name: 'manifests:    plugin.json and mcp.json plugin manifests', value: 'manifests' },
      { name: 'release:      Versioning, tags, and release automation', value: 'release' },
      { name: 'gitflow:      Branching models and repository workflows', value: 'gitflow' },
      { name: 'ci:           GitHub Actions CI/CD workflows', value: 'ci' },
      { name: 'docs:         Documentation and README updates', value: 'docs' },
      { name: 'deps:         Dependencies and package lock updates', value: 'deps' },
      { name: 'config:       Project and tooling configurations', value: 'config' },
      { name: 'workflow:     Agent workflows and test harnesses', value: 'workflow' },
      { name: 'contributing: Contributing guidelines and standards', value: 'contributing' },
    ],
    enableMultipleScopes: false,
    scopeEnumSeparator: ',',
    allowCustomScopes: false,
    allowEmptyScopes: false,
  },
};
